// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PathFinder.Server.Data;

#nullable disable

namespace PathFinder.MigrationService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250730145335_CleanMig")]
    partial class CleanMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PathFinder.Server.Models.Agency", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("FeedId")
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "FeedId");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("PathFinder.Server.Models.FeedInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("FeedEndDate")
                        .HasColumnType("text");

                    b.Property<string>("FeedLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedPublisherName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedPublisherUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedStartDate")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FeedInfos");
                });

            modelBuilder.Entity("PathFinder.Server.Models.Route", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("FeedId")
                        .HasColumnType("text");

                    b.Property<string>("AgencyId")
                        .HasColumnType("text");

                    b.Property<string>("LongName")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id", "FeedId");

                    b.HasIndex("FeedId", "AgencyId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("PathFinder.Server.Models.Stop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("FeedId")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text");

                    b.HasKey("Id", "FeedId");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("PathFinder.Server.Models.Route", b =>
                {
                    b.HasOne("PathFinder.Server.Models.Agency", "Agency")
                        .WithMany("Routes")
                        .HasForeignKey("FeedId", "AgencyId");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("PathFinder.Server.Models.Agency", b =>
                {
                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
