// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PathFinder.Server.Data;

#nullable disable

namespace PathFinder.MigrationService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PathFinder.Server.Models.Stop", b =>
                {
                    b.Property<string>("StopId")
                        .HasColumnType("text");

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("StopLat")
                        .HasColumnType("double precision");

                    b.Property<double>("StopLon")
                        .HasColumnType("double precision");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StopId");

                    b.ToTable("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
